services:
  web-repo-health:
    container_name: web-repo-health
    hostname: web-repo-health
    restart: always
    build:
      context: .
    env_file:
      - .env
    command: >
      sh -c "python manage.py migrate --noinput &&
             python manage.py seed_demo &&
             python manage.py collectstatic --noinput &&
             python manage.py runserver 0.0.0.0:$WEB_PORT"
    volumes:
      - .:/code
    ports:
      - "127.0.0.1:$WEB_PORT:$WEB_PORT"
    depends_on:
      postgres-repo-health:
        condition: service_healthy
      redis-repo-health:
        condition: service_healthy
    networks:
      repo-health-network:
    extra_hosts:
      - "host.docker.internal:host-gateway"

  postgres-repo-health:
    container_name: postgres-repo-health
    hostname: postgres-repo-health
    restart: always
    image: postgres:16-alpine
    env_file:
      - .env
    volumes:
      - postgres-repo-health-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGPORT: ${POSTGRES_PORT}
    command: postgres -p ${POSTGRES_PORT}
    ports:
      - "127.0.0.1:${POSTGRES_PORT}:${POSTGRES_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -p ${POSTGRES_PORT} -U ${POSTGRES_USER}"]
      interval: 2s
      timeout: 3s
      retries: 30
    networks:
      repo-health-network:

  redis-repo-health:
    container_name: redis-repo-health
    hostname: redis-repo-health
    restart: always
    image: redis:7-alpine
    command: --port ${REDIS_PORT}
    ports:
      - "127.0.0.1:${REDIS_PORT}:${REDIS_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -p ${REDIS_PORT} ping"]
      interval: 2s
      timeout: 3s
      retries: 30
    networks:
      repo-health-network:

  celery-repo-health:
    container_name: celery-repo-health
    restart: always
    build:
      context: .
    env_file:
      - .env
    command: celery -A core worker -B -l info -c 4 -Q analysis.user,analysis.scheduled,celery --schedule=/tmp/celerybeat-schedule
    volumes:
      - .:/code
    depends_on:
      postgres-repo-health:
        condition: service_healthy
      redis-repo-health:
        condition: service_healthy
      web-repo-health:
        condition: service_started
    networks:
      repo-health-network:


volumes:
  postgres-repo-health-volume:

networks:
  repo-health-network:
