services:
  web-repo-health-python:
    container_name: web-repo-health-python
    hostname: web-repo-health-python
    restart: unless-stopped
    build:
      context: .
    env_file:
      - .env
    command: >
      sh -c "python manage.py migrate --noinput &&
             python manage.py seed_demo &&
             python manage.py collectstatic --noinput &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "127.0.0.1:${WEB_PORT}:8000"
    depends_on:
      db-repo-health-postgres:
        condition: service_healthy
      redis-repo-health:
        condition: service_healthy

  db-repo-health-postgres:
    container_name: db-repo-health-postgres
    hostname: db-repo-health-postgres
    restart: unless-stopped
    image: postgres:16-alpine
    env_file:
      - .env
    volumes:
      - postgres-repo-health-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGPORT: ${POSTGRES_PORT}
    command: postgres -p ${POSTGRES_PORT}
    ports:
      - "127.0.0.1:${POSTGRES_PORT}:${POSTGRES_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -p ${POSTGRES_PORT} -U ${POSTGRES_USER}"]
      interval: 2s
      timeout: 3s
      retries: 30

  redis-repo-health:
    container_name: redis-repo-health
    hostname: redis-repo-health
    restart: unless-stopped
    image: redis:7-alpine
    command: redis-server --port ${REDIS_PORT}
    ports:
      - "127.0.0.1:${REDIS_PORT}:${REDIS_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -p ${REDIS_PORT} ping"]
      interval: 2s
      timeout: 3s
      retries: 30

  celery-repo-health:
    container_name: celery-repo-health
    restart: unless-stopped
    build:
      context: .
    env_file:
      - .env
    command: celery --app=config worker -B -l info
    volumes:
      - .:/code
    depends_on:
      db-repo-health-postgres:
        condition: service_healthy
      redis-repo-health:
        condition: service_healthy
      web-repo-health-python:
        condition: service_started

volumes:
  postgres-repo-health-volume:
