# Generated by Django 6.1.1 on 2026-09-17 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_slug', models.CharField(max_length=128, verbose_name='организация')),
                ('repo_slug', models.CharField(max_length=128, verbose_name='репозиторий')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('language', models.CharField(blank=True, max_length=64, verbose_name='язык')),
                ('stars', models.PositiveIntegerField(default=0, verbose_name='лайки')),
                ('forks', models.PositiveIntegerField(default=0, verbose_name='форки')),
                ('sourcecraft_id', models.CharField(max_length=255, unique=True, verbose_name='идентификатор SourceCraft')),
                ('url', models.URLField()),
                ('logo_url', models.URLField()),
                ('is_empty', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField()),
                ('visibility', models.CharField(choices=[('public', 'public'), ('internal', 'internal'), ('private', 'private')], max_length=10)),
                ('last_scanned_at', models.DateTimeField(blank=True, null=True, verbose_name='последняя проверка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'репозиторий',
                'verbose_name_plural': 'репозитории',
                'ordering': ['org_slug', 'repo_slug'],
                'unique_together': {('org_slug', 'repo_slug')},
            },
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'в очереди'), ('running', 'идёт'), ('success', 'готово'), ('failed', 'ошибка'), ('partial', 'частично (часть данных недоступна)')], default='pending', max_length=10, verbose_name='статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='завершён')),
                ('raw', models.JSONField(blank=True, default=dict, verbose_name='сырые данные')),
                ('error', models.TextField(blank=True, null=True, verbose_name='ошибка')),
                ('triggered_by', models.CharField(choices=[('schedule', 'по расписанию'), ('user', 'пользователем'), ('manual', 'вручную (management-команда)')], max_length=20, verbose_name='кем запущен')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='health.repository', verbose_name='репозиторий')),
            ],
            options={
                'verbose_name': 'проверка',
                'verbose_name_plural': 'проверки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MetricSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('docs', 'документация и лучшие практики'), ('ci_cd', 'CI/CD'), ('security', 'security'), ('activity', 'активность проекта'), ('issues', 'issues'), ('code_health', 'состояние кода и технический долг')], max_length=15, verbose_name='категория')),
                ('metric_key', models.CharField(max_length=100, verbose_name='например: ci_success_rate_90d, readme_present, todo_count')),
                ('value', models.JSONField(blank=True, null=True, verbose_name='значение метрики (число/строка/структура) или null, если недоступно')),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('is_available', models.BooleanField(default=True, help_text="False = данные недоступны ('нет данных'), не путать со значением 0", verbose_name='доступность')),
                ('error_reason', models.CharField(blank=True, max_length=255, verbose_name='причина недоступности, если is_available=False')),
                ('source_reference', models.CharField(blank=True, max_length=500, verbose_name='ссылка на файл/pipeline/commit/issue/MR, подтверждающая метрику')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_samples', to='health.scan')),
            ],
            options={
                'verbose_name': 'Метрика',
                'verbose_name_plural': 'Метрики',
            },
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=32, verbose_name='категория')),
                ('severity', models.CharField(choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high'), ('critical', 'critical')], max_length=16, verbose_name='серьёзность')),
                ('title', models.CharField(max_length=255, verbose_name='заголовок')),
                ('detail', models.TextField(blank=True, verbose_name='детали')),
                ('recommendation', models.TextField(blank=True, verbose_name='рекомендация')),
                ('evidence_refs', models.JSONField(blank=True, default=list, verbose_name='список ссылок на факты: файлы/pipeline/vulnerability/commit/issue/MR')),
                ('estimated_score_impact', models.SmallIntegerField(default=0, verbose_name='ожидаемый прирост Repo Health Score при устранении проблемы')),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='health.scan', verbose_name='проверка')),
            ],
            options={
                'verbose_name': 'находка',
                'verbose_name_plural': 'находки',
                'ordering': ['severity', 'category'],
            },
        ),
        migrations.CreateModel(
            name='HealthScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('docs', 'документация и лучшие практики'), ('ci_cd', 'CI/CD'), ('security', 'security'), ('activity', 'активность проекта'), ('issues', 'issues'), ('code_health', 'состояние кода и технический долг')], max_length=15, verbose_name='категория')),
                ('total', models.PositiveSmallIntegerField(blank=True, help_text="0-100, null = категория помечена 'Нет данных'", null=True, verbose_name='итого')),
                ('weight_used', models.FloatField(verbose_name='вес категории, фактически применённый при расчёте (после перенормировки)')),
                ('data_completeness', models.FloatField(default=1.0, verbose_name='доля доступных метрик категории, от 0.0 до 1.0')),
                ('raw_metrics', models.JSONField(blank=True, default=dict, verbose_name='снимок значений метрик, использованных в расчёте')),
                ('scan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='health.scan', verbose_name='проверка')),
            ],
            options={
                'verbose_name': 'оценка по категории',
                'verbose_name_plural': 'оценки по категории',
                'unique_together': {('scan', 'category')},
            },
        ),
    ]
