# Generated by Django 5.2.17 on 2026-09-14 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_slug', models.CharField(max_length=128, verbose_name='организация')),
                ('repo_slug', models.CharField(max_length=128, verbose_name='репозиторий')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('language', models.CharField(blank=True, max_length=64, verbose_name='язык')),
                ('stars', models.PositiveIntegerField(default=0, verbose_name='лайки')),
                ('forks', models.PositiveIntegerField(default=0, verbose_name='форки')),
                ('last_scanned_at', models.DateTimeField(blank=True, null=True, verbose_name='последняя проверка')),
            ],
            options={
                'verbose_name': 'репозиторий',
                'verbose_name_plural': 'репозитории',
                'ordering': ['org_slug', 'repo_slug'],
                'unique_together': {('org_slug', 'repo_slug')},
            },
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'в очереди'), ('running', 'идёт'), ('success', 'готово'), ('failed', 'ошибка')], default='pending', max_length=16, verbose_name='статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='завершён')),
                ('raw', models.JSONField(blank=True, default=dict, verbose_name='сырые данные')),
                ('error', models.TextField(blank=True, verbose_name='ошибка')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='health.repository', verbose_name='репозиторий')),
            ],
            options={
                'verbose_name': 'проверка',
                'verbose_name_plural': 'проверки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HealthScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.PositiveSmallIntegerField(default=0, verbose_name='итого')),
                ('activity', models.PositiveSmallIntegerField(default=0, verbose_name='активность')),
                ('community', models.PositiveSmallIntegerField(default=0, verbose_name='сообщество')),
                ('maintenance', models.PositiveSmallIntegerField(default=0, verbose_name='сопровождение')),
                ('documentation', models.PositiveSmallIntegerField(default=0, verbose_name='документация')),
                ('security', models.PositiveSmallIntegerField(default=0, verbose_name='безопасность')),
                ('scan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='health.scan', verbose_name='проверка')),
            ],
            options={
                'verbose_name': 'оценка здоровья',
                'verbose_name_plural': 'оценки здоровья',
            },
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=32, verbose_name='категория')),
                ('severity', models.CharField(choices=[('info', 'info'), ('warning', 'warning'), ('critical', 'critical')], max_length=16, verbose_name='серьёзность')),
                ('title', models.CharField(max_length=255, verbose_name='заголовок')),
                ('detail', models.TextField(blank=True, verbose_name='детали')),
                ('recommendation', models.TextField(blank=True, verbose_name='рекомендация')),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='health.scan', verbose_name='проверка')),
            ],
            options={
                'verbose_name': 'находка',
                'verbose_name_plural': 'находки',
                'ordering': ['severity', 'category'],
            },
        ),
    ]
