# Generated by Django 6.1.1 on 2026-09-18 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_alter_repository_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='logo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
