# Generated by Django 6.1.1 on 2026-09-18 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0003_alter_repository_logo_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repository',
            name='last_updated',
        ),
    ]
