# Generated by Django 6.1.1 on 2026-09-18 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0004_remove_repository_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
