# Generated by Django 6.1.1 on 2026-09-18 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0005_repository_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='org_slug',
            field=models.CharField(max_length=256, verbose_name='организация'),
        ),
        migrations.AlterField(
            model_name='repository',
            name='repo_slug',
            field=models.CharField(max_length=256, verbose_name='репозиторий'),
        ),
    ]
