# Generated by Django 6.1.1 on 2026-09-18 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0006_alter_repository_org_slug_alter_repository_repo_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='logo_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='repository',
            name='org_slug',
            field=models.CharField(max_length=255, verbose_name='организация'),
        ),
        migrations.AlterField(
            model_name='repository',
            name='repo_slug',
            field=models.CharField(max_length=255, verbose_name='репозиторий'),
        ),
        migrations.AlterField(
            model_name='repository',
            name='url',
            field=models.URLField(max_length=255),
        ),
    ]
