# Generated by Django 6.1.1 on 2026-09-18 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0007_alter_repository_logo_url_alter_repository_org_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='repo_slug',
            field=models.CharField(max_length=500, verbose_name='репозиторий'),
        ),
        migrations.AlterField(
            model_name='repository',
            name='url',
            field=models.URLField(max_length=500),
        ),
    ]
